apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-helloworld
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: solutions/argocd/go-manifests
    repoURL: https://github.com/nitinbodke/nd064_course_1
    targetRevision: HEAD
  syncPolicy: {}
